from django.apps import apps
from django.test import TestCase
from .apps import TodoConfig

#testing this would not actually be necessary as the apps.py file is automatically
#generated by django which already has an extensive test suite so we already know
#it will work just fine

class TestTodoConfig(TestCase):
    def test_app(self):
        self.assertEqual("todo", TodoConfig.name)
        self.assertEqual("todo", apps.get_app_config("todo").name)